name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: samruddhig
          DOCKER_PASSWORD: S@mruddhi043
        run: echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin
        
      - name: Build Docker Image
        run: docker build -t samruddhig/cicd-app .
        
        
      - name: Publish Image to Docker Hub
        run: docker push samruddhig/cicd-app:latest


  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull samruddhig/cicd-app:latest
        
      - name: Delete Old Container
        run: docker rm -f reactContainer || true      
      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name reactContainer samruddhig/cicd-app